### ISSUE TITLE
Rendering issue on Safari

### ISSUE THREAD

**Issue by paulbutcher** [flix/api.flix.dev#22]
The menu is displayed incorrectly within Safari:

<img width="134" alt="Screenshot 2022-05-26 at 21 40 14" src="https://user-images.githubusercontent.com/61163/170576399-019a3c45-2497-46f4-8f4d-cade9b2edf23.png">

The culprit seems to be [this](https://github.com/flix/api.flix.dev/blob/master/src/App.css#L80):

```
    -webkit-logical-height: 1em; /* Chrome ignores auto, so we have to use this hack to set the correct height  */
```

Deleting that line fixes the display on Safari and, as far as I can tell, everything still displays OK on Chrome? Was this perhaps a fix for a bug which is now fixed within Chrome? Any reason why this line shouldn't be deleted?

**Comment by magnus-madsen** [comment]
Interesting. What file is this in?

**Comment by magnus-madsen** [comment]
Oh, I see you put the link. Maybe I should just remove that line?

**Comment by paulbutcher** [comment]
That would be my suggestion: the only thing that gives me pause is that I guess it was added for a reason? But when I remove it, things seem to work OK in Chrome, so perhaps whatever the reason was, it no longer holds?

**Comment by magnus-madsen** [comment]
I have deleted the line in #23. Note we don't automatically deploy the api.flix.dev, so you will have to wait for the next manual update :)

**Comment by magnus-madsen** [comment]
Thanks for reporting and happy Flix programming!

**Comment by paulbutcher** [comment]
Thanks!
